const{app,BrowserWindow,dialog,ipcMain,net,shell}=require('electron')
const fs=require('node:fs/promises'),fsNative=require('node:fs'),path=require('node:path'),{createHash}=require('node:crypto'),{Readable}=require('node:stream'),{pipeline}=require('node:stream/promises'),{isNewer,selectAsset}=require('./updater.cjs')
const{loadAgentSkill,loadModelSkillBundle}=require('./skills.cjs')
const root=()=>path.join(app.getPath('userData'),'sudoN'),chats=()=>path.join(root(),'chats'),config=()=>path.join(root(),'config.json'),safe=id=>String(id).replace(/[^a-zA-Z0-9_-]/g,'')
const skillsRoot=()=>path.join(__dirname,'..','skills')
async function json(file,fallback){try{return JSON.parse(await fs.readFile(file,'utf8'))}catch{return fallback}}
async function records(file){const lines=await fs.readFile(file,'utf8').catch(()=> '');return lines.split('\n').filter(Boolean).flatMap(line=>{try{return[JSON.parse(line)]}catch{return[]}})}
async function load(){
 const data=await json(config(),null);if(!data)return null
 const loaded=new Map()
 for(const c of data.conversations??[]){const dir=path.join(chats(),safe(c.id)),meta=await json(path.join(dir,'metadata.json'),{}),raw=await records(path.join(dir,'messages.jsonl')),latest=new Map(raw.map(m=>[m.id,m])),ids=meta.activeMessageIds??[...latest.keys()];loaded.set(c.id,{...c,...meta,messages:ids.map(id=>latest.get(id)).filter(Boolean),checkpoint:await json(path.join(dir,'checkpoint.json'),undefined)})}
 for(const c of loaded.values())if(c.parentChatId&&c.parentMessageId){const parent=loaded.get(c.parentChatId);if(parent){const at=parent.messages.findIndex(m=>m.id===c.parentMessageId);if(at>=0)c.messages=[...parent.messages.slice(0,at+1),...c.messages]}}
 data.conversations=[...loaded.values()];return data
}
async function sync(data){
 await fs.mkdir(chats(),{recursive:true})
 for(const c of data.conversations??[]){
  const dir=path.join(chats(),safe(c.id));await fs.mkdir(path.join(dir,'attachments'),{recursive:true})
  const file=path.join(dir,'messages.jsonl'),raw=await records(file),latest=new Map(raw.map(m=>[m.id,m])),parentAt=c.parentMessageId?c.messages.findIndex(m=>m.id===c.parentMessageId):-1,own=parentAt>=0?c.messages.slice(parentAt+1):c.messages,fresh=own.filter(m=>m.content&&latest.get(m.id)?.content!==m.content)
  if(fresh.length)await fs.appendFile(file,fresh.map(m=>JSON.stringify(m)).join('\n')+'\n')
  await fs.writeFile(path.join(dir,'metadata.json'),JSON.stringify({version:1,id:c.id,title:c.title,createdAt:c.createdAt,updatedAt:c.updatedAt,parentChatId:c.parentChatId,parentMessageId:c.parentMessageId,activeMessageIds:own.filter(m=>m.content).map(m=>m.id)},null,2))
  if(c.checkpoint)await fs.writeFile(path.join(dir,'checkpoint.json'),JSON.stringify(c.checkpoint,null,2))
 }
 const compact={...data,conversations:(data.conversations??[]).map(c=>({...c,messages:[]}))};await fs.writeFile(config(),JSON.stringify(compact,null,2));return true
}
async function search({query,chatId}){const data=await load();if(!data||!query?.trim())return[];const q=query.toLowerCase(),out=[];for(const c of data.conversations??[]){if(chatId&&c.id!==chatId)continue;for(const m of c.messages??[])if(m.content.toLowerCase().includes(q))out.push({chatId:c.id,chatTitle:c.title,messageId:m.id,role:m.role,content:m.content,createdAt:m.createdAt})}return out.slice(-12)}
let syncQueue=Promise.resolve()
ipcMain.handle('store:load',load);ipcMain.handle('store:sync',(_,data)=>{syncQueue=syncQueue.then(()=>sync(data));return syncQueue});ipcMain.handle('history:search',(_,args)=>search(args));ipcMain.handle('store:clear',async()=>{await fs.rm(root(),{recursive:true,force:true});return true})
ipcMain.handle('skill:load',(_,name)=>loadAgentSkill(skillsRoot(),name))
ipcMain.handle('skill:model',(_,model,task)=>loadModelSkillBundle(skillsRoot(),model,task))
ipcMain.handle('web:search',async(_,{query,baseUrl})=>{let endpoint;try{endpoint=new URL('/search',String(baseUrl))}catch{throw new Error('The SearXNG address in Settings is invalid.')}if(!['http:','https:'].includes(endpoint.protocol))throw new Error('The SearXNG address must use HTTP or HTTPS.');endpoint.search=new URLSearchParams({q:String(query).slice(0,400),format:'json',categories:'general',language:'auto',safesearch:'1'}).toString();const response=await net.fetch(endpoint.toString(),{headers:{Accept:'application/json','User-Agent':'sudoN-web-search'}});if(!response.ok)throw new Error(`SearXNG search returned HTTP ${response.status}.`);const data=await response.json();return(data.results??[]).slice(0,5).map(result=>({title:String(result.title??''),url:String(result.url??''),content:String(result.content??'').slice(0,1200)}))})
const releaseApi='https://api.github.com/repos/Jonardi123/local-chat-studio/releases/latest'
async function latestRelease(){const response=await net.fetch(releaseApi,{headers:{Accept:'application/vnd.github+json','User-Agent':'sudoN-updater'}});if(!response.ok)throw new Error(`Update service returned HTTP ${response.status}.`);return response.json()}
function macInstallState(){if(process.platform!=='darwin')return'other';const executable=path.resolve(process.execPath);return executable.startsWith('/Applications/')?'applications':executable.startsWith('/Volumes/')?'disk-image':'elsewhere'}
async function updateInfo(){const release=await latestRelease(),asset=selectAsset(release,process.platform),latest=String(release.tag_name??'').replace(/^v/,'');return{current:app.getVersion(),latest,available:isNewer(latest,app.getVersion()),notes:String(release.body??'').slice(0,4000),assetName:asset?.name??null,assetSize:asset?.size??null,supported:Boolean(asset&&/^sha256:[a-f0-9]{64}$/i.test(String(asset.digest??''))),installState:macInstallState()}}
async function updateDownloadPath(name){const dir=path.join(app.getPath('temp'),'sudoN-updates');await fs.mkdir(dir,{recursive:true});return path.join(dir,path.basename(name))}
ipcMain.handle('update:check',updateInfo)
ipcMain.handle('update:download',async event=>{const release=await latestRelease(),asset=selectAsset(release,process.platform),expected=/^sha256:([a-f0-9]{64})$/i.exec(String(asset?.digest??''))?.[1];if(!asset||!expected||!isNewer(release.tag_name,app.getVersion()))throw new Error('No verified compatible update is available.');const response=await net.fetch(asset.browser_download_url,{headers:{'User-Agent':'sudoN-updater'}});if(!response.ok||!response.body)throw new Error(`Update download returned HTTP ${response.status}.`);const destination=await updateDownloadPath(asset.name),temporary=`${destination}.download`,total=Number(response.headers.get('content-length'))||Number(asset.size)||0,hash=createHash('sha256');let received=0;await fs.rm(temporary,{force:true});const source=Readable.fromWeb(response.body).on('data',chunk=>{hash.update(chunk);received+=chunk.length;event.sender.send('update:progress',{received,total,percent:total?Math.round(received/total*100):null})});try{await pipeline(source,fsNative.createWriteStream(temporary,{flags:'wx'}));if(hash.digest('hex')!==expected.toLowerCase())throw new Error('The downloaded update failed its SHA-256 integrity check.');await fs.rm(destination,{force:true});await fs.rename(temporary,destination)}catch(error){await fs.rm(temporary,{force:true});throw error}const openError=await shell.openPath(destination);if(openError)throw new Error(openError);return{path:destination,installState:macInstallState()}})
function createWindow(){const window=new BrowserWindow({width:1280,height:820,minWidth:360,minHeight:600,backgroundColor:'#f6f4ef',title:'sudoN',autoHideMenuBar:true,webPreferences:{preload:path.join(__dirname,'preload.cjs'),contextIsolation:true,nodeIntegration:false,sandbox:true}});window.webContents.setWindowOpenHandler(({url})=>{if(/^https?:\/\//.test(url))shell.openExternal(url);return{action:'deny'}});window.webContents.on('will-navigate',(event,url)=>{if(url!==window.webContents.getURL()){event.preventDefault();if(/^https?:\/\//.test(url))shell.openExternal(url)}});window.loadFile(path.join(__dirname,'..','dist','index.html'));window.once('ready-to-show',async()=>{if(macInstallState()!=='disk-image')return;const choice=await dialog.showMessageBox(window,{type:'info',title:'Install sudoN',message:'Move sudoN to Applications',detail:'sudoN is running from its installer. Drag sudoN onto the Applications shortcut in the installer, choose Replace if asked, then open sudoN from Applications. This keeps one installed copy and preserves your chats and settings.',buttons:['Show Applications','Continue temporarily'],defaultId:0,cancelId:1});if(choice.response===0)await shell.openPath('/Applications')})}
app.whenReady().then(()=>{createWindow();app.on('activate',()=>{if(BrowserWindow.getAllWindows().length===0)createWindow()})});app.on('window-all-closed',()=>{if(process.platform!=='darwin')app.quit()})
