import { useEffect, useMemo, useRef, useState, type FormEvent } from 'react'
import ReactMarkdown from 'react-markdown'
import remarkGfm from 'remark-gfm'
import { listModels, streamChat } from './api'
import { exportData, loadData, migrateData, normalizeBaseUrl, saveData, STORAGE_KEY } from './storage'
import type { AppData, Conversation, Message, Settings } from './types'
import './App.css'

const uid=()=>crypto.randomUUID()
const suggestions=['Explain quantum computing simply','Draft a friendly project update','Help me debug some code','Plan a productive weekend']

function Markdown({children}:{children:string}){return <ReactMarkdown remarkPlugins={[remarkGfm]} components={{code({className,children,...props}){const block=Boolean(className);const text=String(children).replace(/\n$/,'');return block?<span className="codebox"><span className="codehead"><span>{className?.replace('language-','')||'code'}</span><button onClick={()=>navigator.clipboard.writeText(text)}>Copy</button></span><code className={className}>{text}</code></span>:<code {...props}>{children}</code>}}}>{children}</ReactMarkdown>}

function ConfigForm({initial,onSave,onCancel}:{initial:Settings;onSave:(s:Settings)=>void;onCancel?:()=>void}){
 const [s,setS]=useState(initial),[show,setShow]=useState(false),[models,setModels]=useState<string[]>([]),[status,setStatus]=useState('')
 const patch=(p:Partial<Settings>)=>setS(v=>({...v,...p}))
 const test=async()=>{setStatus('Testing…');try{const next={...s,baseUrl:normalizeBaseUrl(s.baseUrl)};const found=await listModels(next);setModels(found);patch({baseUrl:next.baseUrl,model:s.model||found[0]||''});setStatus(`Connected${found.length?` · ${found.length} model${found.length===1?'':'s'}`:''}`)}catch(e){setStatus(e instanceof Error?e.message:'Connection failed.') }}
 return <form className="config" onSubmit={e=>{e.preventDefault();onSave({...s,baseUrl:normalizeBaseUrl(s.baseUrl)})}}>
  <label>API base URL<input required value={s.baseUrl} onChange={e=>patch({baseUrl:e.target.value})} placeholder="http://192.168.100.6:8080/v1"/></label>
  <label>API key<span className="secret"><input type={show?'text':'password'} value={s.apiKey} onChange={e=>patch({apiKey:e.target.value})} placeholder="Paste your key"/><button type="button" onClick={()=>setShow(v=>!v)}>{show?'Hide':'Show'}</button></span></label>
  <p className="security">Saved only in this browser's localStorage. Use plain HTTP only on a trusted private network.</p>
  <label>Model ID<input list="model-list" value={s.model} onChange={e=>patch({model:e.target.value})} placeholder="Auto-detect or enter manually"/><datalist id="model-list">{models.map(m=><option key={m}>{m}</option>)}</datalist></label>
  <div className="form-actions"><button type="button" className="secondary" onClick={test}>Test connection</button>{onCancel&&<button type="button" className="ghost" onClick={onCancel}>Cancel</button>}<button type="submit">Save{onCancel?' changes':' & continue'}</button></div>
  {status&&<p className={status.startsWith('Connected')?'success':'status'} role="status">{status}</p>}
 </form>
}

function SettingsModal({data,onClose,onChange,onImport}:{data:AppData;onClose:()=>void;onChange:(d:AppData)=>void;onImport:(d:AppData)=>void}){
 const input=useRef<HTMLInputElement>(null);const s=data.settings
 useEffect(()=>{const key=(e:KeyboardEvent)=>e.key==='Escape'&&onClose();addEventListener('keydown',key);return()=>removeEventListener('keydown',key)},[onClose])
 return <div className="backdrop" role="presentation" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><section className="modal" role="dialog" aria-modal="true" aria-labelledby="settings-title"><header><div><span className="eyebrow">Local preferences</span><h2 id="settings-title">Settings</h2></div><button className="icon" onClick={onClose} aria-label="Close">×</button></header>
 <ConfigForm initial={s} onCancel={onClose} onSave={settings=>{onChange({...data,settings});onClose()}}/>
 <div className="setting-grid"><label>Temperature <output>{s.temperature}</output><input type="range" min="0" max="2" step="0.1" value={s.temperature} onChange={e=>onChange({...data,settings:{...s,temperature:+e.target.value}})}/></label><label>Max output tokens<input type="number" min="1" max="32768" value={s.maxTokens} onChange={e=>onChange({...data,settings:{...s,maxTokens:+e.target.value}})}/></label><label>Theme<select value={s.theme} onChange={e=>onChange({...data,settings:{...s,theme:e.target.value as Settings['theme']}})}><option value="system">System</option><option value="light">Light</option><option value="dark">Dark</option></select></label></div>
 <label>System prompt<textarea rows={3} value={s.systemPrompt} onChange={e=>onChange({...data,settings:{...s,systemPrompt:e.target.value}})}/></label>
 <div className="data-tools"><h3>Your data</h3><p>Chats and credentials never leave this browser except requests sent to your chosen server.</p><div><button className="secondary" onClick={()=>exportData(data)}>Export backup</button><button className="secondary" onClick={()=>input.current?.click()}>Import backup</button><input ref={input} hidden type="file" accept="application/json" onChange={async e=>{const f=e.target.files?.[0];if(f)onImport(migrateData(JSON.parse(await f.text())))}}/><button className="danger" onClick={()=>{if(confirm('Delete every conversation, setting, and saved API key?')){localStorage.removeItem(STORAGE_KEY);location.reload()}}}>Clear all</button></div></div>
 </section></div>
}

export default function App(){
 const [data,setData]=useState<AppData>(loadData),[sidebar,setSidebar]=useState(false),[settings,setSettings]=useState(false),[query,setQuery]=useState(''),[draft,setDraft]=useState(''),[error,setError]=useState(''),[generating,setGenerating]=useState(false),[editing,setEditing]=useState<string|null>(null)
 const aborter=useRef<AbortController|null>(null),bottom=useRef<HTMLDivElement>(null),textarea=useRef<HTMLTextAreaElement>(null)
 const change=(next:AppData)=>{setData(next);saveData(next)}
 useEffect(()=>{document.documentElement.dataset.theme=data.settings.theme},[data.settings.theme])
 useEffect(()=>bottom.current?.scrollIntoView({behavior:generating?'auto':'smooth'}),[data.activeId,generating,data.conversations])
 const active=data.conversations.find(c=>c.id===data.activeId)
 const visible=useMemo(()=>data.conversations.filter(c=>c.title.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>b.updatedAt-a.updatedAt),[data.conversations,query])
 const newChat=()=>{const now=Date.now(),c:Conversation={id:uid(),title:'New conversation',messages:[],createdAt:now,updatedAt:now};change({...data,conversations:[c,...data.conversations],activeId:c.id});setSidebar(false);setTimeout(()=>textarea.current?.focus())}
 const updateConversation=(id:string,fn:(c:Conversation)=>Conversation)=>setData(old=>{const next={...old,conversations:old.conversations.map(c=>c.id===id?fn(c):c)};saveData(next);return next})
 const remove=(c:Conversation)=>{if(confirm(`Delete “${c.title}”?`)){const conversations=data.conversations.filter(x=>x.id!==c.id);change({...data,conversations,activeId:data.activeId===c.id?(conversations[0]?.id??null):data.activeId})}}
 const send=async(text=draft,truncateAt?:string)=>{const content=text.trim();if(!content||generating)return;setError('');let conversation=active;if(!conversation){const now=Date.now();conversation={id:uid(),title:content.slice(0,48),messages:[],createdAt:now,updatedAt:now};change({...data,conversations:[conversation,...data.conversations],activeId:conversation.id})}let prior=truncateAt?conversation.messages.slice(0,conversation.messages.findIndex(m=>m.id===truncateAt)):conversation.messages;const user:Message={id:uid(),role:'user',content,createdAt:Date.now()},assistant:Message={id:uid(),role:'assistant',content:'',createdAt:Date.now()};const id=conversation.id;const title=prior.length?conversation.title:content.slice(0,48);updateConversation(id,c=>({...c,title,messages:[...prior,user,assistant],updatedAt:Date.now()}));setDraft('');setEditing(null);setGenerating(true);const ctl=new AbortController();aborter.current=ctl
  try{const messages=[...(data.settings.systemPrompt?[{role:'system' as const,content:data.settings.systemPrompt}]:[]),...prior.map(m=>({role:m.role,content:m.content})),{role:'user' as const,content}];const result=await streamChat({settings:data.settings,messages,signal:ctl.signal,onToken:full=>updateConversation(id,c=>({...c,messages:c.messages.map(m=>m.id===assistant.id?{...m,content:full}:m)}))});updateConversation(id,c=>({...c,messages:c.messages.map(m=>m.id===assistant.id?{...m,...result}:m),updatedAt:Date.now()}))}catch(e){if(!(e instanceof DOMException&&e.name==='AbortError')){setError(e instanceof Error?e.message:'Generation failed.');updateConversation(id,c=>({...c,messages:c.messages.filter(m=>m.id!==assistant.id)}))}}finally{setGenerating(false);aborter.current=null}}
 const regenerate=()=>{if(!active)return;const last=active.messages.findLast(m=>m.role==='user');if(last)send(last.content,last.id)}
 if(!data.onboarded)return <main className="onboarding"><div className="brandmark">L</div><span className="eyebrow">Your AI. Your hardware.</span><h1>Meet Local Chat</h1><p className="lead">A private, focused workspace for the OpenAI-compatible model running on your own network.</p><ConfigForm initial={data.settings} onSave={s=>change({...data,settings:s,onboarded:true})}/></main>
 return <div className="app"><button className="mobile-menu" onClick={()=>setSidebar(true)} aria-label="Open conversations">☰</button>{sidebar&&<div className="sidebar-shade" onClick={()=>setSidebar(false)}/>}<aside className={sidebar?'open':''}><div className="brand"><span className="brandmark">L</span><b>Local Chat</b><button className="icon mobile-close" onClick={()=>setSidebar(false)}>×</button></div><button className="new" onClick={newChat}><span>＋</span> New conversation</button><label className="search"><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search conversations" aria-label="Search conversations"/></label><nav aria-label="Conversations">{visible.length===0?<p className="muted">No conversations yet.</p>:visible.map(c=><div className={`chat-row ${c.id===data.activeId?'active':''}`} key={c.id}><button onClick={()=>{change({...data,activeId:c.id});setSidebar(false)}}><span>{c.title}</span><small>{new Date(c.updatedAt).toLocaleDateString()}</small></button><button className="row-action" title="Rename" onClick={()=>{const name=prompt('Conversation name',c.title);if(name?.trim())updateConversation(c.id,x=>({...x,title:name.trim()}))}}>✎</button><button className="row-action" title="Delete" onClick={()=>remove(c)}>×</button></div>)}</nav><div className="sidebar-foot"><button onClick={()=>setSettings(true)}>⚙ <span>Settings</span></button><small>{data.settings.model||'Automatic model'}</small></div></aside>
 <main className="chat"><header><div><span className="online-dot"/>Local server</div><button className="secondary" onClick={()=>setSettings(true)}>Settings</button></header><section className="messages" aria-live="polite">{!active||active.messages.length===0?<div className="empty"><div className="orb">L</div><h1>How can I help?</h1><p>Ask your local model anything. Your conversations stay on this device.</p><div className="suggestions">{suggestions.map(s=><button key={s} onClick={()=>send(s)}>{s}<span>↗</span></button>)}</div></div>:<div className="thread">{active.messages.map(m=><article className={`message ${m.role}`} key={m.id}><div className="avatar">{m.role==='user'?'Y':'L'}</div><div className="bubble"><div className="message-head"><b>{m.role==='user'?'You':'Local AI'}</b><time>{new Date(m.createdAt).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}</time></div>{editing===m.id?<form onSubmit={e=>{e.preventDefault();send(draft,m.id)}}><textarea value={draft} onChange={e=>setDraft(e.target.value)} autoFocus/><div><button>Save & send</button><button type="button" className="ghost" onClick={()=>setEditing(null)}>Cancel</button></div></form>:m.content?<Markdown>{m.content}</Markdown>:<span className="typing"><i/><i/><i/></span>}<div className="message-tools"><button onClick={()=>navigator.clipboard.writeText(m.content)}>Copy</button>{m.role==='user'&&!generating&&<button onClick={()=>{setEditing(m.id);setDraft(m.content)}}>Edit</button>}{m.role==='assistant'&&m.elapsedMs&&<small>{(m.elapsedMs/1000).toFixed(1)}s{m.tokensPerSecond?` · ${m.tokensPerSecond.toFixed(1)} tok/s`:''}</small>}</div></div></article>)}{error&&<div className="error" role="alert">{error} <button onClick={regenerate}>Try again</button></div>}<div ref={bottom}/></div>}</section>
 <footer className="composer-wrap"><form className="composer" onSubmit={(e:FormEvent)=>{e.preventDefault();send()}}><textarea ref={textarea} rows={1} value={draft} onChange={e=>setDraft(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send()}}} placeholder="Message your local model…" aria-label="Message"/><div className="compose-foot"><span>Enter to send · Shift+Enter for newline</span>{generating?<button type="button" className="stop" onClick={()=>aborter.current?.abort()}>■ Stop</button>:<button className="send" disabled={!draft.trim()} aria-label="Send">↑</button>}</div></form><p>AI can make mistakes. Verify important information.</p></footer></main>{settings&&<SettingsModal data={data} onClose={()=>setSettings(false)} onChange={change} onImport={d=>{change(d);setSettings(false)}}/>}</div>
}
